USE task_crud;

CREATE TABLE STATS (
	STAT_ID INT(11) NOT NULL AUTO_INCREMENT ,
	STAT_DATE DATETIME NOT NULL,
	STAT VARCHAR(20) NOT NULL,
	VALUE INT(11) NOT NULL,
	PRIMARY KEY (`STAT_ID`)
);

CREATE VIEW BESTSELLERS_COUNT AS 
	SELECT COUNT(*) FROM BOOKS WHERE BESTSELLER = true;
    
DELIMITER $$
CREATE EVENT UPDATE_COUNT_BESTSELLERS
	ON SCHEDULE EVERY 1 MINUTE DO
    BEGIN
		DECLARE AMOUNT_BESTSELLERS int(5);
		CALL UpdateBestsellers();
		SELECT * FROM BESTSELLERS_COUNT INTO amount_bestsellers;
		INSERT INTO stats(STAT_DATE,STAT,VALUE) values (curtime(),"BESTSELLERS", AMOUNT_BESTSELLERS);
    END$$
DELIMITER ;